{% set name = "dm-sonnet" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/sonnet/archive/v{{ version }}.tar.gz
  sha256: 73c0046681488b3000f8af5e8fdfc4363a12babef6246306c669d74b538152a3

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - absl-py >=0.7.1
    - six >=1.12.0
    - tensorflow >=1.0.1

test:
  imports:
    - sonnet
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepmind/sonnet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Sonnet is a library built on top of TensorFlow 2 designed to provide simple, composable abstractions for machine learning research.
  description: |
    Sonnet has been designed and built by researchers at DeepMind.
     It can be used to construct neural networks for many different
     purposes (un/supervised learning, reinforcement learning, ...).
     More specifically, Sonnet provides a simple but powerful programming
     model centered around a single concept: snt.Module. Modules can hold
     references to parameters, other modules and methods that apply some
     function on the user input. Sonnet ships with many predefined modules
     (e.g. snt.Linear, snt.Conv2D, snt.BatchNorm) and some predefined networks
     of modules (e.g. snt.nets.MLP) but users are also encouraged to build their
     own modules.
  doc_url: https://sonnet.readthedocs.io/en/latest/
  dev_url: https://github.com/deepmind/sonnet

extra:
  recipe-maintainers:
    - marcelotrevisani
    - asmith26
    - maresb
    - thewchan
